#! /bin/sh

FIRST_DESK=0
REMAINING_DESKS='1 3 4 5 6 7 8 9'
bspc rename Desktop01 $FIRST_DESK
bspc add $REMAINING_DESKS

bspc rule Gimp Eight floating

bspc set border_width        0
bspc set window_gap          0
bspc set borderless_monocle  true
bspc set gapless_monocle     true
bspc set adaptative_raise    true
bspc set top_padding         15
