#!/usr/bin/env ruby 

class Host
	attr_accessor :alias, :host, :user
end

hosts = []

file = File.new("/users/arcus/.zsh/ssh/config", "r")
while (line = file.gets)
	line_words = line.split(' ')
	if line_words[0] == 'Host'
		hosts.push(Host.new)
		hosts[hosts.length-1].alias = line_words[1]
	end

	if line_words[0] == 'HostName'
		hosts[hosts.length-1].host = line_words[1]
	end

	if line_words[0] == 'User'
		hosts[hosts.length-1].user = line_words[1]
	end
end

hosts.each do |h|
	puts h.alias+": "+h.user+'@'+h.host
end
file.close
